import { StyleSheet } from 'react-native';
import { OS, fontSizes, height, width } from './utils';
import colors from './colors';
import fonts from '../assets/fonts/fonts';

const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    // paddingHorizontal: 10,
    backgroundColor: colors.background,
  },
  bottomSpace: {
    height: OS === 'ios' ? 26 : 10,
    backgroundColor: colors.background,
  },
  placeholder: {
    fontSize: fontSizes.regular,
    color: colors.primaryBlack,
    fontFamily: fonts.medium,
  },
  error: {
    color: 'red',
    fontSize: 14,
    // marginStart: 4,
    minHeight: 12,
    marginVertical: 5,
  },
  radioError: {
    color: 'red',
    fontSize: 14,
    marginStart: 4,
    marginBottom: 5,
  },
  titleTxt: {
    fontFamily: fonts.bold,
    fontSize: 16,
    fontWeight: '600',
    color: colors.title,
  },
  label: {
    color: colors.label,
    fontSize: 15,
    fontFamily: fonts.medium,
    fontWeight: '400',
    marginVertical: 15,
  },
  noDataText: {
    color: colors.label,
    fontSize: 15,
    fontFamily: fonts.medium,
    fontWeight: '400',
    marginVertical: 15,
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnWidth: {
    width: '46%',
  },
  grayBtn: {
    width: '46%',
    height: 50,
  },
  smallHeightBtn: {
    width: '47.5%',
    height: 40,
  },
  rowBtnWidth: {
    width: '48%',
    height: 46,
  },
  dotRowContainer: {
    flexDirection: 'row',
    padding: 10,
  },
  pointsTxt: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: fonts.regular,
    color: colors.text,
    paddingHorizontal: 15,
  },
  infoRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  labelTxt: {
    color: colors.text2,
    fontFamily: fonts.medium,
    fontSize: 14,
    fontWeight: '500',
    width: '50%',
  },
  dataTxt: {
    color: colors.title,
    fontFamily: fonts.medium,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'left',
    width: '50%',
  },
  bottomFooter: {
    backgroundColor: colors.white,
    alignSelf: 'center',
    padding: 15,
  },
  commonTxt: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: fonts.regular,
    color: colors.label,
  },
  tagTxt: {
    color: colors.icon,
    fontFamily: fonts.medium,
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 8,
  },
  price: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.title,
    marginBottom: 10,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 15,
  },
  dateTxt: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: fonts.regular,
    color: colors.label,
  },
  logOutBtn: {
    marginVertical: 15,
    backgroundColor: colors.btnSecondary,
  },
  logOutBtnTxt: {
    color: colors.white,
  },
  iconStyle: {
    tintColor: colors.white,
  },
  accountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 25,
  },
  accountTxt: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: fonts.medium,
    color: colors.text3,
  },
  signUpTxt: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: fonts.medium,
    color: colors.primary,
    marginLeft: 5,
  },
  headerRowContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    // width: width,
    // marginStart: 4,
    paddingHorizontal: 10,
    width:'100%',
    // right: 10,
    // left: 10,
  },
  reimbursementContainer: {
    backgroundColor: colors.white,
    padding: 15,
    borderRadius: 20,
    marginVertical: 15,
  },
  downloadBtn: { width: 264, alignSelf: 'center' },
  noDataContainer: {
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
    padding: 15,
    borderRadius: 12,
    marginVertical: height / 3.5,
  },
  noDataTxt: {
    fontSize: 18,
    fontWeight: '400',
    fontFamily: fonts.regular,
    color: colors.primaryBlack,
    textAlign: 'center',
  },
  floatingAction: {
    position: 'absolute',
    bottom: 40,
    right: 16,
    borderRadius: 100,
    backgroundColor: colors.primary,
  },
  serviceList: {
    backgroundColor: colors.white,
    padding: 15,
    borderRadius: 142,
    borderColor: colors.border,
    borderWidth: 1,
    height: 70,
    marginBottom: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  services: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primaryTint,
    borderRadius: 50,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 5,
    width: '100%',
  },
  serviceTxt: {
    color: colors.placeholder,
    fontSize: 14,
    fontFamily: fonts.regular,
    fontWeight: '400',
    marginHorizontal: 5,
  },
  onPressText: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: fonts.medium,
    color: colors.primary,
    textAlign: 'center',
    marginVertical: 20,
  },
  serviceInfo: {
    backgroundColor: colors.white,
    marginVertical: 15,
    borderRadius: 20,
    padding: 15,
  },
  serviceInfoLabel: {
    fontWeight: '500',
    fontSize: 14,
    fontFamily: fonts.medium,
    color: colors.label,
    marginBottom: 20,
  },
  description: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: fonts.regular,
    color: colors.label,
    marginBottom: 20,
  },
  primaryLabel: {
    fontWeight: '500',
    fontSize: 14,
    fontFamily: fonts.medium,
    color: colors.primary,
    marginBottom: 10,
  },
  input: {
    height: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: colors.border,
    // marginBottom: 15,
    backgroundColor: "green"
  },
  inputValue: {
    fontSize: 16,
    color: colors.text,
    fontFamily: fonts.regular,
    fontWeight: '400',
  },
  expLabel: {
    color: colors.label,
    fontSize: 14,
    fontWeight: '500',
    fontFamily: fonts.medium,
    marginBottom: 15,
  },
  mainContainer: {
    width: '100%',
  },
  inputWrapper: {
    height: 48,
    paddingHorizontal: 14,
    borderRadius: 25,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5
  },
  // input: {
  //   height: 40,
  //   flex: 1,
  //   justifyContent: 'center',
  // },
  // placeholder: {
  //   color: colors.placeholder,
  //   fontFamily: fonts.medium,
  //   fontSize: 14,
  //   fontWeight: '500',
  // },
  valueText: {
    color: colors.black,
    fontFamily: fonts.medium,
    fontSize: 14,
    fontWeight: '500',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.white,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    height: height,
  },
  searchContainer: {
    paddingHorizontal: 20,
    marginTop: 12,
    height: 50,
  },
  searchInput: {
    borderWidth: 1,
    borderRadius: 150,
    borderColor: colors.border,
    height: 40,
    paddingHorizontal: 15,
    fontSize: 14,
    fontFamily: fonts.medium,
    fontWeight: '500',
    color: colors.primary,
  },
  countryItem: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    fontSize: 14,
    fontFamily: fonts.medium,
    fontWeight: '500',
    color: colors.primary,
  },
  flatListContent: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
});
export default commonStyles;
